server:
  redirect-url: http://localhost:8080/
spring:
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    mode : HTML5
    cache : false
  jwt:
    secret_key: Tin9iMoSahSsJ7q

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/simplestudy?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql